// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseProjectFolder() {
  return window['go']['main']['App']['ChooseProjectFolder']();
}

export function CreateMarkdownFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMarkdownFile'](arg1, arg2, arg3);
}

export function ExportMarkdownPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportMarkdownPDF'](arg1, arg2, arg3);
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function OpenFile(arg1, arg2) {
  return window['go']['main']['App']['OpenFile'](arg1, arg2);
}

export function RefreshProjectTree(arg1) {
  return window['go']['main']['App']['RefreshProjectTree'](arg1);
}

export function RestoreLastProject() {
  return window['go']['main']['App']['RestoreLastProject']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SaveWorkspaceState(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWorkspaceState'](arg1, arg2, arg3, arg4);
}
