// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ChooseProjectFolder():Promise<models.ProjectSnapshot>;

export function CreateMarkdownFile(arg1:string,arg2:string,arg3:string):Promise<models.CreatedFileResult>;

export function ExportMarkdownPDF(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetInitialState():Promise<models.AppState>;

export function OpenFile(arg1:string,arg2:string):Promise<models.FileDocument>;

export function RefreshProjectTree(arg1:string):Promise<Array<models.TreeNode>>;

export function RestoreLastProject():Promise<models.ProjectSnapshot>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<models.FileDocument>;

export function SaveWorkspaceState(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<void>;
